name: Build WASM
on:
  push: 
    branches:
    - master
jobs:
  build_wasm:
    name: Build WebAssembly Package & deploy demo
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
      - name: Yarn install
        run: cd crates/wasm/js-demo && yarn
      - name: Yarn build (dev)
        if: github.event_name == 'pull_request'
        run: cd crates/wasm/js-demo && yarn build -d
      - name: Yarn build (prod)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: cd crates/wasm/js-demo && yarn build -p
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./crates/wasm/js-demo/dist
